class Steps:

    SELECT_TYPE = "SELECT_TYPE"

    LEAVE_TYPE = "LEAVE_TYPE"
    LEAVE_DATES = "LEAVE_DATES"

    MISSION_LOCATION = "MISSION_LOCATION"
    MISSION_DATES = "MISSION_DATES"
    MISSION_DESCRIPTION = "MISSION_DESCRIPTION"

    WAITING_OVERTIME = "WAITING_OVERTIME"
    WAITING_REMOTE = "WAITING_REMOTE"